export const UPDATE_POST = "UPDATE_POST";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const LOGOUT = "LOGOUT";

export const CLEAR_AUTH_STATE = "CLEAR_AUTH_STATE";

export const EDIT_USER_SUCCESSFUL = "EDIT_USER_SUCCESSFUL";
export const EDIT_USER_FAILED = "EDIT_USER_FAILED";

export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILED = "USER_PROFILE_FAILED";
export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";

export const FETCH_FRIEND_SUCCESS = "FETCH_FRIEND_SUCCESS";

export const ADD_FRIEND = "ADD_FRIEND";
export const REMOVE_FRIEND = "REMOVE_FRIEND";

export const CREATE_POST = "CREATE_POST";
export const ADD_COMMENT = "ADD_COMMENT";

export const UPDATE_POST_LIKE = "UPDATE_POST_LIKE";

export const FETCH_SEARCH_RESULTS_SUCCESS = "FETCH_SEARCH_RESULTS_SUCCESS";


